config/routes.rb
Rails.application.routes.draw do

  root 'bookings#welcome'
  post '/welcome',:to => 'bookings#available'
  post '/available' => 'bookings#create'

  get 'admin', :to => 'admin#login'
  get 'admin/menu', :to => 'admin#menu'
  get 'admin/login', :to => 'admin#login'
  get 'admin/logout', :to => 'admin#logout'
  get 'admin/show', :to => 'admin#show'
  post 'admin/attempt_login', :to => 'admin#attempt_login'

  get 'admin/new' => 'admin#new'
  post 'admin/new' => 'admin#create'

  resources :bookings
  resources :rooms
  resources :room_types

end

app/views/admin/login.erb
<% @page_title = "Admin Login" %>

<div class="login">
  <%= form_tag(:action => 'attempt_login') do %>
      <table>
        <tr>
          <td><%= label_tag(:name) %></td>
          <td><%= text_field_tag(:name) %></td>
        </tr>
        <tr>
          <td><%= label_tag(:password) %></td>
          <td><%= password_field_tag(:password) %></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td><%= submit_tag('Log In') %></td>
        </tr>
      </table>
  <% end %>
</div>

app/views/admin/menu.erb
<% @page_title = 'Admin menu' %>

<div class='menu'>
  <h1>Administration Menu</h1>
  <ul>
    <li><%= link_to('Manage Rooms', :controller => 'rooms') %></li>
    <li><%= link_to('Manage Type of rooms', :controller => 'room_types') %></li>
    <li><%= link_to('Manage Booking', :controller => 'bookings') %></li>
    <li><%= link_to('Manage Admins', :action => 'show') %></li>
    <li><%= link_to('Logout', :action => 'logout') %></li>
  </ul>
</div>

app/views/admin/new.erb
<% @page_title = 'Create new admin' %>

<div class="login">
  <%= form_tag(:action => 'new') do %>
      <table>
        <tr>
          <td><%= label_tag(:name) %></td>
          <td><%= text_field_tag(:name) %></td>
        </tr>
        <tr>
          <td><%= label_tag(:password) %></td>
          <td><%= password_field_tag(:password) %></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td><%= submit_tag('Create') %></td>
        </tr>
      </table>
  <% end %>
</div>

app/views/admin/show.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
  <tr>
    <th>Person</th>
    <th>Password</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @admins.each do |ad| %>
          <tr>
            <td><%= ad.name %></td>
            <td><%= ad.password_digest%></td>
            <td><%#= link_to 'Delete', admin_path(ad), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
  </tbody>
</table>
<%= link_to 'Add administrator', :action => 'new' %>
<%= link_to 'Back to menu', admin_menu_path %>
<br>