config/routes.rb
Rails.application.routes.draw do

  root 'bookings#welcome'
  post '/welcome',:to => 'bookings#available'
  post '/available' => 'bookings#create'

  get 'admin', :to => 'admin#login'
  get 'admin/menu', :to => 'admin#menu'
  get 'admin/login', :to => 'admin#login'
  get 'admin/logout', :to => 'admin#logout'
  get 'admin/show', :to => 'admin#show'
  post 'admin/attempt_login', :to => 'admin#attempt_login'

  get 'admin/new' => 'admin#new'
  post 'admin/new' => 'admin#create'

  resources :bookings
  resources :rooms
  resources :room_types

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :room

  @@rooms = Array.new

  validates_presence_of :number
  validates_numericality_of :number
  validates_presence_of :begining
  validates_presence_of :ending
  validates :cost, numericality: { greater_than: 0 }, presence: true
  validate :number_must_exist
  validate :dates_correct


  def number_must_exist
    unless @@rooms.include? self.number
    errors.add(:number, 'Must exist')
    end
  end


  def dates_correct
    if self.begining < Date.today || self.ending < Date.tomorrow || self.begining>self.ending
          errors.add(:number, 'Select correct date')
    end
  end

  def self.allowed_for_booking (d_st,d_end)
    all_rooms = Room.all
    room_numbers = all_rooms.pluck(:number)
    all_bookings = Booking.all

    year_now = Date.today.year
    if d_st.year > year_now
      d_st_mod = d_st.yday + 365
    else
      d_st_mod = d_st.yday
    end

    if d_end.year > year_now
      d_end_mod = d_end.yday + 365
    else
      d_end_mod = d_end.yday
    end

    all_bookings.each do |b|

        if b[:begining].year > year_now
          b_st_mod = b[:begining].yday + 365
        else
          b_st_mod = b[:begining].yday
        end
        if b[:ending].year > year_now
          b_end_mod = b[:ending].yday + 365
        else
          b_end_mod = b[:ending].yday
        end

      #------------------
        if ((b_st_mod...b_end_mod) === d_st_mod) ||
            ((b_st_mod...b_end_mod) === d_end_mod)
          if room_numbers.include? (b[:number])
            room_numbers.delete(b[:number])
          end
        end

        if (b_st_mod >= d_st_mod) && (b_end_mod <= d_end_mod)
          if room_numbers.include? (b[:number])
            room_numbers.delete(b[:number])
          end
        end

=begin
        if ((b[:begining].yday...b[:ending].yday) === d_st.yday) ||
            ((b[:begining].yday...b[:ending].yday) === d_end.yday)
          if room_numbers.include? (b[:number])
            room_numbers.delete(b[:number])
          end
        end
        #
        if (b[:begining].yday >= d_st.yday) && (b[:ending].yday <= d_end.yday)
          if room_numbers.include? (b[:number])
            room_numbers.delete(b[:number])
          end
        end
=end
      end
     #in array room_numbers left only available for booking for selected date
    @@rooms = room_numbers
    return room_numbers
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
    # GET /bookings
  # GET /bookings.json
  def index
    @rtype = RoomType.all
    if session.has_key?(:name) && session.has_key?(:id)
      @bookings = Booking.all
    else
      redirect_to(:action => 'welcome')
    end
  end

  def welcome
    @booking = Booking.new
  end

  def available
    d_st = params[:d_st]
    @ds = Date.new(d_st['(1i)'].to_i, d_st['(2i)'].to_i, d_st['(3i)'].to_i)

    d_end = params[:d_en]
    @de = Date.new(d_end['(1i)'].to_i, d_end['(2i)'].to_i, d_end['(3i)'].to_i)

    @bookings = Booking.new
    @rtypes = RoomType.all
    @rooms = Room.find(Booking.allowed_for_booking(@ds,@de))
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @rtype = RoomType.all
    if session.has_key?(:name) && session.has_key?(:id)

    else
      redirect_to(:action => 'welcome')
    end

  end

   # GET /bookings/new
  def new
    @rtype = RoomType.all
    if session.has_key?(:name) && session.has_key?(:id)
      @booking = Booking.new
    else
      redirect_to(:action => 'welcome')
    end
  end

  # GET /bookings/1/edit
  def edit
    if session.has_key?(:name) && session.has_key?(:id)

    else
      redirect_to(:action => 'welcome')
    end
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @r_type = RoomType.all
    @booking = Booking.new(booking_params)
    if session.has_key?(:name) && session.has_key?(:id)
      respond_to do |format|
        if @booking.save
        @room = Room.all
      #  tmp = @booking['number']-1
       # @room[tmp].status = true
       # @room[tmp].save
          format.html { render :show , notice: 'Booking was successfully created.' }
          format.json { render :show , status: :created, location: @booking }
        else
          @room = Room.all
          format.html { render :new }
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @booking.save
          @room = Room.all
        #  tmp = @booking['number']-1
        #  @room[tmp].status = true
        #  @room[tmp].save
          @room = Room.free
          format.html { render :welcome, notice: 'Booking was successfully created.' }
          format.json { render :welcome, status: :created, location: @booking }
        else
          @room = Room.free
          format.html { render :welcome }
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
      end
      end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    if session.has_key?(:name) && session.has_key?(:id)
      respond_to do |format|
        if @booking.update(booking_params)
          format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
          format.json { render :show, status: :ok, location: @booking }
        else
          format.html { render :edit }
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
      end

    else
      redirect_to(:action => 'welcome')
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    if session.has_key?(:name) && session.has_key?(:id)
      @booking.destroy
      @room = Room.all
     # tmp = @booking['number']-1
     # @room[tmp].status = false
     # @room[tmp].save
      respond_to do |format|
        format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to(:action => 'welcome')
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:number, :begining, :ending, :cost)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>

  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, 'error') %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :begining %><br>
    <%= f.date_select :begining %>
  </div>
  <div class="field">
    <%= f.label :ending %><br>
    <%= f.date_select :ending %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/available.html.erb
<%= form_for(@bookings) do |f| %>
    <h2> Welcome to room booking system</h2>

    <h3>Select one of this rooms:</h3>
    <table>
      <thead>
      <tr>
        <th>Number</th>
        <th>Type</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @rooms.each do |f| %>
          <tr>
            <td><%= f.number %></td>
            <td><%= @rtypes[f.type_id-1].type_name %></td>
            <td><%= f.price %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <div class="field">
      <%= f.label :begining %><br>
      <%= f.date_select :begining, default: @ds %>
    </div>
    <div class="field">
      <%= f.label :ending %><br>
      <%= f.date_select :ending, default: @de %>
    </div>

    <div class="field">
      <%= f.label :number %><br>
      <%= f.number_field :number %>
    </div>

    <div class="field">
      <%= f.label :cost %><br>
      <%= f.number_field :cost %>
    </div>
    <%=f.submit %>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', admin_menu_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Begining</th>
      <th>Ending</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |bk| %>
      <tr>
        <td><%= bk.number %></td>
        <td><%= bk.begining %></td>
        <td><%= bk.ending %></td>
        <td><%= bk.cost %></td>
        <td><%= link_to 'Show', bk %></td>
        <td><%= link_to 'Edit', edit_booking_path(bk) %></td>
        <td><%= link_to 'Delete', bk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>
<%= link_to 'Back to menu', admin_menu_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Number:</strong>
  <%= @booking.number %>
</p>

<p>
  <strong>Begining:</strong>
  <%= @booking.begining %>
</p>

<p>
  <strong>Ending:</strong>
  <%= @booking.ending %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @booking.cost %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/ushow.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Number:</strong>
  <%= @booking.number %>
</p>

<p>
  <strong>Begining:</strong>
  <%= @booking.begining %>
</p>

<p>
  <strong>Ending:</strong>
  <%= @booking.ending %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @booking.cost %>
</p>

<%= link_to 'Back', root_path %>

app/views/bookings/welcome.html.erb
<%= form_tag('/welcome') %>
<% @page_title = 'Welcome' %>
<h2> Welcome to room booking system</h2>
    <h3> Select date: </h3>
    <p> From:<%= date_select(:d_st, '' ) %></p>
    <p> To:<%= date_select(:d_en, '' ) %></p>
    <%=submit_tag value='Accept date' %>