config/routes.rb
Rails.application.routes.draw do

  root 'bookings#welcome'
  post '/welcome',:to => 'bookings#available'
  post '/available' => 'bookings#create'

  get 'admin', :to => 'admin#login'
  get 'admin/menu', :to => 'admin#menu'
  get 'admin/login', :to => 'admin#login'
  get 'admin/logout', :to => 'admin#logout'
  get 'admin/show', :to => 'admin#show'
  post 'admin/attempt_login', :to => 'admin#attempt_login'

  get 'admin/new' => 'admin#new'
  post 'admin/new' => 'admin#create'

  resources :bookings
  resources :rooms
  resources :room_types

end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController
  before_action :set_room_type, only: [:show, :edit, :update, :destroy]

  # GET /room_types
  # GET /room_types.json
  def index
    @room_types = RoomType.all
  end

  # GET /room_types/1
  # GET /room_types/1.json
  def show
    if session.has_key?(:name) && session.has_key?(:id)

    else
      redirect_to(:action => 'index')
    end
  end

  # GET /room_types/new
  def new
    (session.has_key?(:name) && session.has_key?(:id)) ? @room_type = RoomType.new : redirect_to(:action => 'index')
  end

  # GET /room_types/1/edit
  def edit
    if session.has_key?(:name) && session.has_key?(:id)

    else
      redirect_to(:action => 'index')
    end
  end

  # POST /room_types
  # POST /room_types.json
  def create
    if session.has_key?(:name) && session.has_key?(:id)
      @room_type = RoomType.new(room_type_params)

      respond_to do |format|
        if @room_type.save
          format.html { redirect_to @room_type, notice: 'Room type was successfully created.' }
          format.json { render :show, status: :created, location: @room_type }
        else
          format.html { render :new }
          format.json { render json: @room_type.errors, status: :unprocessable_entity }
        end
      end

    else
      redirect_to(:action => 'index')
    end
  end

  # PATCH/PUT /room_types/1
  # PATCH/PUT /room_types/1.json
  def update
    if session.has_key?(:name) && session.has_key?(:id)
      respond_to do |format|
        if @room_type.update(room_type_params)
          format.html { redirect_to @room_type, notice: 'Room type was successfully updated.' }
          format.json { render :show, status: :ok, location: @room_type }
        else
          format.html { render :edit }
          format.json { render json: @room_type.errors, status: :unprocessable_entity }
        end
      end

    else
      redirect_to(:action => 'index')
    end

  end

  # DELETE /room_types/1
  # DELETE /room_types/1.json
  def destroy
    if session.has_key?(:name) && session.has_key?(:id)
      @room_type.destroy
        respond_to do |format|
        format.html { redirect_to room_types_url, notice: 'Room type was successfully destroyed.' }
        format.json { head :no_content }
      end

    else
      redirect_to(:action => 'index')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_type
      @room_type = RoomType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_type_params
      params.require(:room_type).permit(:type_name)
    end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/room_types/_form.html.erb
<%= form_for(@room_type) do |f| %>
  <% if @room_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room_type.errors.count, "error") %> prohibited this room_type from being saved:</h2>

      <ul>
      <% @room_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_name %><br>
    <%= f.text_field :type_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/room_types/edit.html.erb
<h1>Editing Room Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @room_type %> |
<%= link_to 'Back', room_types_path %>

app/views/room_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Room Types</h1>

<table>
  <thead>
    <tr>
      <th>Type name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_types.each do |room_type| %>
      <tr>
        <td><%= room_type.type_name %></td>
        <td><%= link_to 'Show', room_type %></td>
        <td><%= link_to 'Edit', edit_room_type_path(room_type) %></td>
        <td><%= link_to 'Delete', room_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room type', new_room_type_path %>
<%= link_to 'Back to menu', admin_menu_path %>

app/views/room_types/new.html.erb
<h1>New Room Type</h1>

<%= render 'form' %>

<%= link_to 'Back', room_types_path %>

app/views/room_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type name:</strong>
  <%= @room_type.type_name %>
</p>

<%= link_to 'Edit', edit_room_type_path(@room_type) %> |
<%= link_to 'Back', room_types_path %>