config/routes.rb
Rails.application.routes.draw do

  root 'bookings#welcome'
  post '/welcome',:to => 'bookings#available'
  post '/available' => 'bookings#create'

  get 'admin', :to => 'admin#login'
  get 'admin/menu', :to => 'admin#menu'
  get 'admin/login', :to => 'admin#login'
  get 'admin/logout', :to => 'admin#logout'
  get 'admin/show', :to => 'admin#show'
  post 'admin/attempt_login', :to => 'admin#attempt_login'

  get 'admin/new' => 'admin#new'
  post 'admin/new' => 'admin#create'

  resources :bookings
  resources :rooms
  resources :room_types

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_one :room_type
  has_many :bookings

  validates_uniqueness_of :number
  validates_presence_of :number
  validates_presence_of :type_id
  validates_inclusion_of :status, :in => [true, false]
  validates_presence_of :price

  scope :free, -> { where(:status => false) }

=begin
  def allowed_for_booking (d_st,d_end)
    ##set room.status = free if nobody book the room for this period
    all_rooms = Room.all
    room_numbers = all_rooms.pluck(:number)

    all_rooms.each() do |room|
      #finding all entries of booking for this room
      currentBooking = room.bookings.find # Booking.all
      currentBooking.each do |cb|
        if (d_st < cb[:ending] || d_end > cd[:begining])
          if room_numbers.include? (cb[:number])
            room_numbers - cb[:number]
          end
        end
      end
    end

    #in array room_numbers left only available for booking for selected date
    return room_numbers
  end
=end

end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
  belongs_to :room

  validates :type_name, :presence => true, :length => { :maximum => 50 }

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    if session.has_key?(:name) && session.has_key?(:id)
      @rooms = Room.all
      @is_admin = true
    else
      @rooms = Room.free
      @is_admin = false
    end
  end

  #def available
   # @rooms = Room.find(allowed_for_booking(@booking[:begining],@booking[:ending]))
   # @is_admin = false
  #end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    if session.has_key?(:name) && session.has_key?(:id)

    else
      redirect_to(:action => 'index')
    end
  end

  # GET /rooms/new
  def new
    if session.has_key?(:name) && session.has_key?(:id)
    @room = Room.new

    else
      redirect_to(:action => 'index')
    end
  end

  # GET /rooms/1/edit
  def edit
    if session.has_key?(:name) && session.has_key?(:id)

    else
      redirect_to(:action => 'index')
    end
  end

  # POST /rooms
  # POST /rooms.json
  def create
    if session.has_key?(:name) && session.has_key?(:id)
      @room = Room.new(room_params)

      respond_to do |format|
        if @room.save
          format.html { redirect_to @room, notice: 'Room was successfully created.' }
          format.json { render :show, status: :created, location: @room }
        else
          format.html { render :new }
          format.json { render json: @room.errors, status: :unprocessable_entity }
        end
      end

    else
      redirect_to(:action => 'index')
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    if session.has_key?(:name) && session.has_key?(:id)
      respond_to do |format|
        if @room.update(room_params)
          format.html { redirect_to @room, notice: 'Room was successfully updated.' }
          format.json { render :show, status: :ok, location: @room }
        else
          format.html { render :edit }
          format.json { render json: @room.errors, status: :unprocessable_entity }
        end
      end

    else
      redirect_to(:action => 'index')
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    if session.has_key?(:name) && session.has_key?(:id)
      @room.destroy
      respond_to do |format|
        format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
        format.json { head :no_content }
      end

    else
      redirect_to(:action => 'index')
    end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:number, :type_id, :price, :status)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/available.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
  <tr>
    <th>Number</th>
    <th>Type</th>
    <th>Price</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @rooms.each do |room| %>
      <tr>
        <td><%= room.number %></td>
        <td><%= room.type_id %></td>
        <td><%= room.price %></td>
        <td><%= room.status %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Type</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.number %></td>
        <td><%= room.type_id %></td>
        <td><%= room.price %></td>
        <td><%= room.status %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>
<%= link_to 'Back to menu', admin_menu_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @room.number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @room.type_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>